### ISSUE TITLE
not aware of tiling window managers

### ISSUE THREAD

**Issue by vifm9** [seebye/ueberzug#100]
image preview can be all over the screen regardless of where the preview actually is.
tried with vifm with i3wm.

**Comment by seebye** [comment]
1. Any code related to window managers doesn't belong in this project.  
2. Unreleated to i3wm I just tested it with Xephyr, i3wm and xterm.  

> image preview can be all over the screen regardless 

I don't really get what you mean.  
If you're using a daemon terminal and the images appear in another terminal:  
Daemon terminals aren't supported
