### ISSUE TITLE
Error: No matches found

### ISSUE THREAD

**Issue by dominikheinz** [seebye/ueberzug#101]
Hey,
I am trying to get the example script to work to display an image in my terminal:
                                   
```
source "`ueberzug library`"

{
    ImageLayer::add [identifier]="example0" [x]="0" [y]="0" [path]="pic.jpg"
    read
} | ImageLayer
```
Running it with source results in the error: `imgprev.sh:4: no matches found: [identifier]=example0`

**Comment by seebye** [comment]
The library is going to be deprecated.  
Build a command of an action of the protocol instead of calling the functions like it's done in https://github.com/seebye/ueberzug/blob/master/examples/fzfimg.sh or https://github.com/seebye/fzf-ueberzogen.  

Example:
```bash
{
    declare -pA addCommand=([action]="add" [identifier]="example0" [x]="0" [y]="0" [path]="pic.jpg")
} | ueberzug layer --parser bash
```

**Comment by dominikheinz** [comment]
Applying this change yields a different error:
`/home/user/.local/lib/python3.8/site-packages/ueberzug/lib/lib.sh: line 6: `String::trim': not a valid identifier`

**Comment by seebye** [comment]
You need to remove `source "`ueberzug library`"`.
