### ISSUE TITLE
ueberzug awareness of urxvtd

### ISSUE THREAD

**Issue by vifm9** [seebye/ueberzug#103]
it would be very nice i think if ueberzug would play nice with the daemon feature of urxvt
since it saves quiet a bit of memory and image previews are not cheap.

**Comment by seebye** [comment]
That's unlikely to happen as it goes against the design concept of this program of how to determine the window of a process.  
As far as I know there's no way to figure out which pseudo tty is represented on a window.  
There's no standard which makes this possible as far as I know.  
According to theoretical computer science every problem is unsolvable if it's not trivial.  
So figuring this out is a undecidable problem which should be provable with e.g. the theorem of rice.
(The current model also only works thanks to the free desktop standard.)
