### ISSUE TITLE
Fails to work when wrapped inside script

### ISSUE THREAD

**Issue by slavistan** [seebye/ueberzug#108]
Hi there!

I'm writing a little wrapper to setup a client-server application to preview images which includes an instance of ueberzug listening to a named pipe in the background. Consider this simple script which implements a *setup* and a *show* command, where the former creates the fifo and spawns the ueberzug background process and the latter sends the appropriate commands to the fifo to generate an overlay. 

```sh
#!/usr/bin/env sh
case "$1" in
  setup)
    { rm fifo; killall ueberzug; } 2>/dev/null
    mkfifo fifo
    ( tail -f fifo | ueberzug layer -p json )&
    ;;
  show)
    echo '{"action": "add","identifier": "default","x": 0,"y": 0,"path": "file.jpg"}' > fifo
    sleep 2
    echo '{"action": "remove","identifier": "default"}' > fifo
    ;;
esac
```

If I attempt to run the script above `./script.sh setup; ./script.sh show` no image appears, although paradoxically, everything works as expected If I copypaste the respective code into my shell verbatim. 

After some tinkering, I noticed that creating a background subshell `( ... )&` causes the spawned process to be detached** from the process tree of the shell which executes the script, and hence to be detached from the terminal for which I want to generate the overlay. From a quick glance into your source code you seem to traverse the process tree in order to find the nearest terminal which may be the root of the problem.

**by *detached* I'm trying to describe what I see in my `htop` process view: Normal commands run by the script are shown as branches connected to the process of the calling shell and hence the terminal. But the `ueberzug` background process is located in a different branch altogether. This is sort of what it looks like:

```
 /sbin/init splash
 ├─ /usr/local/bin/st zsh        # <- my terminal where I want the overlay
 │  └─ sh ./script.sh            # <- the wrapper script
 │      ├─ command_a
 │      └─ command_b
 .
 .  # below is the ueberzug background process, completely detached from the above
 .
 ├─ sh ./script.sh setup
 │  ├─ /usr/bin/python3 /usr/local/bin/ueberzug layer -p json
 │  │  ├─ /usr/bin/python3 /usr/local/bin/ueberzug layer -p json
 │  │  ├─ /usr/bin/python3 /usr/local/bin/ueberzug layer -p json
 │  │  ├─ /usr/bin/python3 /usr/local/bin/ueberzug layer -p json
 │  │  ├─ /usr/bin/python3 /usr/local/bin/ueberzug layer -p json
 │  │  ├─ /usr/bin/python3 /usr/local/bin/ueberzug layer -p json
 │  │  ├─ /usr/bin/python3 /usr/local/bin/ueberzug layer -p json
 │  │  ├─ /usr/bin/python3 /usr/local/bin/ueberzug layer -p json
 │  │  ├─ /usr/bin/python3 /usr/local/bin/ueberzug layer -p json
 │  │  ├─ /usr/bin/python3 /usr/local/bin/ueberzug layer -p json
 │  │  ├─ /usr/bin/python3 /usr/local/bin/ueberzug layer -p json
 │  │  ├─ /usr/bin/python3 /usr/local/bin/ueberzug layer -p json
 │  │  ├─ /usr/bin/python3 /usr/local/bin/ueberzug layer -p json
 │  │  ├─ /usr/bin/python3 /usr/local/bin/ueberzug layer -p json
 │  │  ├─ /usr/bin/python3 /usr/local/bin/ueberzug layer -p json
 │  │  ├─ /usr/bin/python3 /usr/local/bin/ueberzug layer -p json
 │  │  └─ /usr/bin/python3 /usr/local/bin/ueberzug layer -p json
 │  └─ tail -f fifo
```

Any ideas?

**Comment by slavistan** [comment]
After some further tinkering, I can confirm that this is independent of the shell used (dash, bash, zsh). Background processes in subshells get detached from the process tree and are reattached as children of the init process and I have not found a way to circumvent this.

There is nothing `ueberzug` can do about this, but as a quick fix I suggest an option to pass the pid of one's terminal (or any pid of the process tree), e.g. `ueberzug layer --pid 4423 -p json`. Would that be something reasonable to implement?

**Comment by seebye** [comment]
> From a quick glance into your source code you seem to traverse the process tree in order to find the nearest terminal which may be the root of the problem.

That's right ueberzug uses the process tree to figure out which process is the youngest parent process with a X11 window.  
So this is nothing unexpected.  
Also I think it's obvious:  
Let your shell be the process A.  
If you execute your script a new process will be created, process B.  
So the process tree looks something like this:  
Init - .... - A - B  
As your script executes ueberzug a new process C will be created.  
Process tree: Init - .... - A - B - C  
As soon as the script is executed completely process B will die and C becomes an infant and will therefore be collected by the (sub-/)reaper.  
The reaper should be process 1 / systemd / your init system.  
So obviously the process tree looks now like this: Init - C  
So it's quite obvious that this is the case in every shell.  

Ueberzug should only live as long as it's used so your structure has to be a tree (not including the init process).  
So I don't really see the point in creating a ueberzug instance while running an active shell,  
but it can be solved like the **concept** scripts I provided for [vifm](https://old.reddit.com/r/linux/comments/aviu08/ueberzug_v1810_released/ehgpv6y/).  
So you can just run another shell (in your setup clause) and make sure to do a clean up (things like rm fifo, kill ueberzugpid) after you're done.  

> { rm fifo; killall ueberzug; } 2>/dev/null

That's quite offtopic, but don't do this.  
This kills every ueberzug process not only yours.

**Comment by slavistan** [comment]
Thanks a lot for the reply. Indeed, I wasn't aware that orphans are always adopted by pid 1 (in my book the grandparent process would've been a justifiable choice aswell). That explains `ueberzug`'s behavoir.

> Ueberzug should only live as long as it's used so your structure has to be a tree

I think this is a non sequitur. I want to use `ueberzug` while the structure of the involved processes is not a tree due to forces beyond my control (i.e. the linux kernel's reparenting policy). I intended to implement a general purpose image previewer for terminal applications akin to my dummy script above *without* forcing the user to wrap his application inside a script as your vifm scripts do. For the same reason one cannot enable `ueberzug` previews in vim as the background process `!tail -f pipe | ueberzug ... &` would be detached in the same fashion.

A *--pid* option is really all it takes to get rid of all the above problems. When `ueberzug` is instantiated inside a script the tree structure is still intact while the subprocess is still running and thus `ueberzug --pid $$ ...` would either do the trick or, at least, `$$` could be used to get to the terminal's pid. Additionally, this would allow me to open terminals and initialize previews in a true client-server fashion like this.

```sh
#!/usr/bin/env sh
mkfifo fifo
$TERMINAL &
tail -f fifo | ueberzug --pid $! layer -p json &
```

But this is material for a separate issue. I'll have a deeper look into the code and maybe we'll figure something out. As far as I'm concerned this issue may be closed.

Thank you.
