### ISSUE TITLE
100% percent cpu usage while trying to preview an image in ranger

### ISSUE THREAD

**Issue by jedi2610** [seebye/ueberzug#113]
cpu is at full throttle when trying to preview an image in ranger.
not just one image though. this usually happens if the image file is bigger.
CPU: Ryzen 5 2600

**Comment by jedi2610** [comment]
is there a log file that i can add?

**Comment by seebye** [comment]
No there is none.  
Also I can't reproduce this with the provided information.  
Even for images with the resolution 6000x4000 there is just a high cpu usage for a short time (which is obvious as decoding images is expensive).  
Even for png it behaves the same for me and in my experience png's are expensive to decode.

**Comment by jedi2610** [comment]
no it's like it's stuck in a loop while decoding those images and it doesn't preview them even after like 30 seconds.

**Comment by seebye** [comment]
You could try to display the image using a bash script (as error messages are hidden if ueberzug is used by ranger as ueberzug is started with the silent flag):  
```bash
{
       declare -A -p c=([action]=add [identifier]=0 [x]=0 [y]=0 [width]=50 [height]=10 [path]="path to your image")
       sleep 5;
} | ueberzug layer --parser bash
```

This way it's possible to see (1) if it's an issue with ranger (2) if pillow prints error messages.  
If it won't lead to anything (/won't display the image + prints no error message) it would make sense to provide the image to reproduce the error.  
If it's not possible to reproduce it it would make sense to check the dependencies as python sucks a little in this subject. (see e.g. https://github.com/seebye/ueberzug/issues/112)  
E.g. pillow-simd also lead to problems in the past (not sure if it changed)

**Comment by jedi2610** [comment]
it does display the image. so i guess it's a problem with ranger then.
