### ISSUE TITLE
Images do not appear most of the time.

### ISSUE THREAD

**Issue by Filip62** [seebye/ueberzug#114]
Hi,

I run Alacritty on Arch Linux.

If I run
`ueberzug layer`

and then pass it this json line
`{"action": "add", "x": 5, "y": 5, "path": "/home/filip/Downloads/vifmimg-master/screenshot.png", "identifier": "ID1", "width": 32, "height": 18}`

the image does not appear. I tried changing the parameters and the image but still nothing worked.

The weird thing is that it worked once, but absolutely nothing was changed.
I remember trying to get it to work in the past and it did the exact same thing, sometimes it worked and other times without any obvious reason it did not.

I would appreciate help, of course I will try any suggestions. Thank you.

**Comment by seebye** [comment]
Try to install ueberzug in a virtual environment and test whether it works.  

```shell
$ # commands should be executed in a bash shell:
$ python3 -m virtualenv venv
$ source venv/bin/activate
$ which pip
$ # should print a path pointing to a file in your venv
$ pip install ueberzug
$ which ueberzug
$ # should print a path pointing to a file in your venv
$ { declare -A -p c=([action]=add [identifier]=0 [x]=5 [y]=5 [width]=32 [height]=18 [path]="/home/filip/Downloads/vifmimg-master/screenshot.png"); sleep 5; } | ueberzug layer --parser bash
$ # the image should appear for 5 seconds
```

**Comment by Filip62** [comment]
The venv was set up properly but the image did not appear.

**Comment by Filip62** [comment]
So it worked the second time I ran this line in the venv
`$ { declare -A -p c=([action]=add [identifier]=0 [x]=5 [y]=5 [width]=32 [height]=18 [path]="/home/filip/Downloads/vifmim`
and also afterwards.
So I tried in another terminal instance, inside the venv, outside the venv, it did not work.
I tried again in the original terminal(I did not close it) inside the venv and it still worked.

**Comment by seebye** [comment]
> Also I forgot tomention that I followed install instructions for SIMD pillow, but that should not matter since it worked once.

As far as I know SIMD instruction aren't always used by pillow-simd so this does matter.  
So did you also install it in the venv?  
If yes recreate the venv as instructed.  
Also are there any errors printed?

**Comment by Filip62** [comment]
No I did not install simd pillow in the venv, I did exactly what you described in your first reply. In the venv there are no errors, outside of venv also no errors.

**Comment by Filip62** [comment]
After a restart it does not work again in the venv created as described.

**Comment by seebye** [comment]
Do you use fish as shell?

**Comment by Filip62** [comment]
Yes I do.
I'm so sorry if it is something important and I did not mention it.
But the venv test was done through bash running under fish.

Dňa st 16. 9. 2020, 13:29 seebye <notifications@github.com> napísal(a):

**Comment by seebye** [comment]
Fishs changes information about the window size which is normally provided by the terminal emulator see:  
https://github.com/seebye/ueberzug/issues/116#issuecomment-692813104
