### ISSUE TITLE
Image previewing using ueberzug does not immediately work in Ranger, Vifm (Vifmimg) with Fish + any terminal (Known issue with Fish 3.0.3-3.1.2 modifying TIOCGWINSZ. Fix for now is compiling Fish from latest branch or waiting for next release.)

### ISSUE THREAD

**Issue by kwand** [seebye/ueberzug#116]
I've been running into a strange issue that I've been trying to debug for hours, but without much luck at all.

What happens is both Ranger (using the standard ueberzug preview config.) and Vifm (using Vifmimg - scripts here [[1] vifmimg](https://github.com/sdushantha/dotfiles/blob/master/vifm/.config/vifm/scripts/vifmimg), [[2] vifmrun](https://github.com/sdushantha/bin/blob/master/utils/vifmrun)) do not immediately* show a file preview when 'hovering' over it with the selection; normally, of course, it should display the file preview immediately after the file is selected.

_Note: *By "not immediately", I don't mean that it starts working after a certain amount of time, but rather that I need to do a few workarounds (described below) to get it working_

Kitty is my current default terminal (in which it doesn't work), but I've just discovered today that everything appears to work normally - using Ranger and Vifm - on Urxvt and the standard GNOME Terminal. Though, that's not much of a solution as I don't use those terminals anymore. The same problem seems to appear on Alacrity too.

The workaround that I've been using to get file previews to show is to first get Ranger/Vifm to open the selected file, then close the file, which seems to get the file preview to be drawn. 
- With Ranger, this seems to fix the issue immediately as I can go select the next file and a preview will instantly appear. 
- With Vifm (which is my preferred file manager), the workaround is more complicated as the file preview is just stuck in the preview window - selecting different files doesn't clear the preview - and I have to exit Vifm to resolve it. Though, upon opening Vifm again, everything seems to behave normally.

But this only 'fixes' things for that specific instance of the terminal. Once I exit Kitty/Alacritty and open a new instance of it, everything is broken again. 

I assume this has something to do with ueberzug acquring the terminal instance to draw on, or maybe Kitty detecting ueberzug trying to do so? As it appears once it can draw something (broken or not, in terms of clearing the preview), it continues to work fine for as long as I'm using the same terminal instance. In fact, I just tried using Ranger to first perform the workaround (simply opening a file - the Ranger-specific workaround described above), then when switching to Vifm on the same instance, file previewing there starts working instantly (without needing to do the long Vifm workaround described above).

____

I've looked through most of the open/closed issues here, including #115, but I can't seem to find something that describes my case - or I'm not quite sure how to check. In regards to the common issues you listed in #115:

- I'm on X11, not Wayland (using i3wm on Manjaro)
- Not using pillow-simd.
- _NET_WM_PID seems to be set. `xprop` returns a "_NET_WM_PID(CARDINAL)" property that is set, for example (in one run), to "82893".
- Not quite sure what a "sandbox" is referring to.
- Kitty does appear to have a daemon mode - which I just found out in the process of searching for a solution - but I don't think it's on by default. And I don't launch Kitty with any commands other than `kitty -e 'usr/bin/fish'`. Different instances of Kitty also appear to return different _NET_WM_PID(CARDINAL) values via `xprop`, so I assume this implies it is not running in daemon mode.
- Not sure if _NET_CLIENT_LIST is set or not.
- Images don't seem to be corrupted; again, previewing works fine on GNOME Term, Urxvt (and on Kitty, after performing workarounds)

I've also tried the script you provided there, and it works; I can get an image to appear through there (on Kitty).

_________________________________

Also, I don't have anything special set up on Kitty - this is my config file:

```
include ~/.cache/wal/colors-kitty.conf

font_family Fira Code
bold_font Fira Code Bold
italic_font Fira Code Italic
bold_italic_font Fira Code Italic

font_size 11.0

window_padding_width 18.0

remember_window_size no
initial_window_width 640
initial_window_height 440

sync_to_monitor no
```

**Comment by seebye** [comment]
> I assume this has something to do with ueberzug acquring the terminal instance to draw on, or maybe Kitty detecting ueberzug trying to do so? 

- ueberzug 18.1.6:  
  * if there's no image visible:
    Check before running ranger / vifm whether there are multiple windows with the pid of the terminal emulator.  
    I think the following command should list the windows.  
    ```bash
    echo ${PPID}
    pstree -sp ${PPID}  # ppid should be the pid of the terminal emulator otherwise just replace ${PPID} in the following command with the pid of the terminal emulator
    xdotool search --all --pid ${PPID}
    ```
     (The information is only interessting for situations where ueberzug wasn't able to show anything.)
  * if there's no image visible: Was ueberzug able to create a child window within the terminal?
    You can check this by:
    
    + running `xwininfo -tree`
    + clicking on the terminal emulator
    
     The last line of the output should be "{some value} children."
     Do this before starting ranger / vifm and after you tried to preview an image in ranger / vifm and check whether the children count increased.
- There were some changes in the latest version to improve the support of embed ptys, so: Does this also happen with ueberzug 18.1.5?

**Comment by kwand** [comment]
OK, I've tested them out:

**ueberzug 18.1.6:**
  - Nothing interesting seemed to happen. This is what happened in one run:
```bash
6325   # echo ${PPID}
systemd(1)---kitty(6323)---fish(6325)---bash(7040)---pstree(7300)   # pstree -sp ${PPID}
# Nothing came back from "xdotool search --all --pid ${PPID}.
29360139 # xdotool search --all --pid 6323
```
And, to be sure, this is what came back in another run in a different terminal instance:
```bash
7809
systemd(1)---kitty(7797)---fish(7809)---bash(7837)---pstree(7910)
# Again nothing from the first run.
33554443 # with pid as "7797"
```

  - Vifm has a child immediately after launching (which I suppose is not surprising since in the `vifmrun` launch script, ueberzug is also listening immediately), while Ranger does not until I attempt to preview something. And there seems to be a child whether or not an image appears. As a note, my native resolution is `3440 x 1440`.

_**Ranger**:_ 

```Bash
# Before launching ranger; also, this is a brand new terminal instance.
xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x1c0000b "fish /home/dkwan"

  Root window id: 0x1dc (the root window) "i3"
  Parent window id: 0x400106 "[i3 con] container around 0x5579cc5e77d0"
     0 children.

# After launching ranger.
xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x1c0000b "ranger /home/dkwan"

  Root window id: 0x1dc (the root window) "i3"
  Parent window id: 0x400106 "[i3 con] container around 0x5579cc5e77d0"
     0 children.

# Attempting to preview an image (nothing appears).
xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x1c0000b "ranger /home/dkwan"

  Root window id: 0x1dc (the root window) "i3"
  Parent window id: 0x400106 "[i3 con] container around 0x5579cc5e77d0"
     1 child:
     0x1e00001 (has no name): ()  1127x1390+0+0  +2298+35

# Workaround performed; image appears.
xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x1c0000b "ranger /home/dkwan"

  Root window id: 0x1dc (the root window) "i3"
  Parent window id: 0x400106 "[i3 con] container around 0x5579cc5e77d0"
     1 child:
     0x1e00001 (has no name): ()  1127x1390+0+0  +2298+35
```
_**Vifm** (using the vifmrun script, mentioned in previous comment)_
```Bash
# Before launching vifm; also a brand new terminal instance 
xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x1c0000b "fish /home/dkwan"

  Root window id: 0x1dc (the root window) "i3"
  Parent window id: 0x40011c "[i3 con] container around 0x5579cc5dd450"
     0 children.

# ...
# For the sake of brevity, I get the exact same result x5 after launching vifm, attempting
# to a view an image (unsuccesfully), and after performing the workaround (opening the image - preview appears, then attempting to view another image - last preview stuck, then
restarting vifm and viewing previews (succesfully) again)
xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x1c0000b "vifmrun /home/dkwan"

  Root window id: 0x1dc (the root window) "i3"
  Parent window id: 0x40011c "[i3 con] container around 0x5579cc5dd450"
     1 child:
     0x1e00001 (has no name): ()  1127x1390+0+0  +2298+35

```

**ueberzug 18.1.5**

I installed the "python-ueberzug 18.1.5-3" package from Manjaro community repository. From a quick glance (and running the same commands), nothing seems to be different i.e. still broken, and the commands give back the same results as above. And I have to perform the same workarounds to get images to display.

**Comment by seebye** [comment]
Well, I guess I found the issue.  
TIOCGWINSZ reports wrong width & heights if fish is a parent process.  
Some times the correct values are returned sometimes they aren't,  
so the image is likely drawn somewhere out of the visible area of the terminal emulator.  
So this looks like a race condition and indeed it seems like fish messed with these information.  
However it seems like they removed it a few months ago ( https://github.com/fish-shell/fish-shell/commit/d5a239e59ec0e84a47d499270f618e432abd747f ) at least I can't find any other occurence of TIOCSWINSZ in their code.  
The latest version of fish doesn't contain these changes so *maybe* it works with the latest version of fish but I guess you would need to compile it yourself as the latest release is from april and the changes were made in june.

**Comment by kwand** [comment]
Ah, yes. You're right. It seems to be actually working after compiling from latest commit.

I made the mistake (in EDIT 5) of running the latest commit version inside the latest release (3.1.2) - which I forgot also causes an issue as long as fish 3.1.2 was a parent process somewhere along the chain.

I'll put in a correction in my last comment (EDIT 5) about the latest commit not working, in case someone reads that and skips this.

I'm not sure if this should be now closed or left open until the next version of fish is released? I'll update the title to better reflect the issue + note the fix.
