### ISSUE TITLE
Preview problem with Wayland in Ranger

### ISSUE THREAD

**Issue by mordax777** [seebye/ueberzug#118]
**Description**
I am trying to use Ueberzug in Ranger to preview the images. Till the beginning of May, it was working as expected, and this was the last time I was using it. Today I tried using Ranger again and saw that the image preview stopped working.

**Setup**
OS: Arch Linux x86_64
Shell: fish 3.1.2
DE: GNOME
WM: Mutter
Terminal: kitty

**Foundings**
I tried reverting Ueberzug to the version which I had installed in May, did not help. I was cleaning up my system few weeks ago, might have deleted some required packages for the x11/wayland integration, but no errors in the Journal that would point to the problem. Tried using ZSH, did not help

Was able to preview a image in Ranger, but only when I open a second tab in the same terminal window. How to reproduce:
* Open Ranger
* Navigate to a picture
* Open a new tab
* Picture should appear in terminal
It appears that it works only when opening a second tab, but what is strange is that the image preview appears in all the tab's and not just in the one running Ranger. What is also interesting is that I tried using the GNOME Terminal with the "workaround", and it does not work there.

**Comment by seebye** [comment]
Wayland is unsupported & you're on your own if you want to use ueberzug with it.
