### ISSUE TITLE
better documentation

### ISSUE THREAD

**Issue by ghistes** [seebye/ueberzug#120]
Hi,

I would like to integrate ueberzug into my file-manager but at the moment I cannot figure out how to use ueberzug properly (my fault probably as I do not have a lot of python-skills).

Could you provide a few example scripts for common use-cases that illustrate how to use it?

I can make your "general example" work, but I am at a loss to tweak it so that an image is displayed at a specific location, scaled to certain max_x and max_y coordinates...

Many thanks!

**Comment by seebye** [comment]
Well, could you give some more details?
What exactly do you think is missing?

> (my fault probably as I do not have a lot of python-skills).

It's **not** a requirement to use ueberzug with python.  
The protocol is explained in the readme.  

Also I enabled the wiki on this repository in case anyone wants to add something.
