### ISSUE TITLE
TerminalInfo returns xpixels and ypixels as 65535

### ISSUE THREAD

**Issue by msalihcaliskan** [seebye/ueberzug#124]
Ueberzug was not working on my system when I try to use with vifm. The problem was ioctl returns 65535 for both xpixels and ypixels values. I applied below patch and working now.

```diff
diff --git a/ueberzug/terminal.py b/ueberzug/terminal.py
index eff857e..0eba0ce 100644
--- a/ueberzug/terminal.py
+++ b/ueberzug/terminal.py
@@ -18,6 +18,10 @@ class TerminalInfo:
         farg = struct.pack("HHHH", 0, 0, 0, 0)
         fretint = fcntl.ioctl(fd_pty, termios.TIOCGWINSZ, farg)
         rows, cols, xpixels, ypixels = struct.unpack("HHHH", fretint)
+
+        xpixels = xpixels if xpixels != 65535 else 0
+        ypixels = ypixels if ypixels != 65535 else 0
+
         return cols, rows, xpixels, ypixels

     @staticmethod

```
Maybe this is only my system problem however, I would like to inform you.

**Comment by seebye** [comment]
These values are (usually) set by the pseudo terminal master (=your terminal emulator),  
but other programs can change these values also.  
E.g. the developers of the fish shell had the great idea of messing with these values.  
I'm not going to implement this patch as it does not follow the documentation of the values.  
See "Get and set window size" in https://man7.org/linux/man-pages/man4/tty_ioctl.4.html

**Comment by msalihcaliskan** [comment]
I am using fish shell. I think it would be appreciated, If you add a notice to fish shell users about this potential problem. Of course, that's up to you.

**Comment by seebye** [comment]
Ok, then fish should be the cause for this issue.  
related: https://github.com/seebye/ueberzug/issues/116#issuecomment-692813104
