### ISSUE TITLE
Ueberzug leaves windows/processes open

### ISSUE THREAD

**Issue by Strahinja** [seebye/ueberzug#125]
With the latest update (ueberzug 18.1.6-3 package from Artix Linux repository), preview windows in ranger 1.9.3-3 with `set preview_images_method ueberzug` stay open, leaving ueberzug processes open. This also happens in [fontpreview-ueberzug-git r19.63e6b4c-1][2] in Artix Linux, since it depends on ueberzug, which is using the Artix package, which uses 18.1.6 version of ueberzug).

If I switch instead to AUR package [python-ueberzug-git 18.1.5.a8ac9c3-1][1], the issue doesn't manifest.

More details [in this thread][3].

[1]: https://aur.archlinux.org/packages/python-ueberzug-git/
[2]: https://aur.archlinux.org/packages/fontpreview-ueberzug-git/
[3]: https://forum.artixlinux.org/index.php/topic,2041.msg13651.html#msg13651

**Comment by seebye** [comment]
I already dealed with this in
https://github.com/seebye/ueberzug/commit/2aa5c0ea3bca2d0699ac0570629a1b518ea68b5e
and https://github.com/seebye/ueberzug/pull/119  
I didn't released a new version which contains the changes yet.

**Comment by Strahinja** [comment]
I see. I will close this then. Any ETA on when will this be released?

**Comment by seebye** [comment]
I published the current state of the master branch as version 18.1.7
