### ISSUE TITLE
ueberzug doesnt work with ranger 

### ISSUE THREAD

**Issue by siduck76** [seebye/ueberzug#130]
ueberzug was working few hours ago for me , Im not sure what caused the issue now and it shows like this : 
 
![d](https://user-images.githubusercontent.com/59060246/101381289-96dda200-38dc-11eb-9d01-82c3f9045c0f.png)

**Comment by seebye** [comment]
That's not an ueberzug error as visible in the stacktrace an error occurs in the psutil project.

**Comment by siduck76** [comment]
ueberzug was working before idk why doesnt work now :(

**Comment by siduck76** [comment]
![image](https://user-images.githubusercontent.com/59060246/101429526-2b6df180-3929-11eb-95a2-49e87827eea8.png)
