### ISSUE TITLE
Image doesn't appear anymore.

### ISSUE THREAD

**Issue by TornaxO7** [seebye/ueberzug#131]
Hello! I have this little test-script:
`test.sh`
```bash
#!/bin/bash
ueberzug layer --parser bash 0< <(declare -Ap add_command=([action]="add" [identifier]="test" [x]="0" [y]="0" [path]="/windows/Images/rest/pikachu.jpg"))
sleep 1
```

Here's my file structure:
![image](https://user-images.githubusercontent.com/50843046/101961687-87c36080-3c0a-11eb-996c-46aa41dc6a91.png)

As you can see the file exist, but if I run the script nothing happens. What am I doing wrong?
![GIF](https://user-images.githubusercontent.com/50843046/101961778-be00e000-3c0a-11eb-8566-93212721df67.gif)

**Comment by TornaxO7** [comment]
Oh bruh... the `sleep` command needed to be inside of the bracket... sorry, my mistake.... it's working now!

**Comment by seebye** [comment]
ueberzug exists on EOF.  

Changing your code to

```bash
#!/bin/bash
ueberzug layer --parser bash 0< <(declare -Ap add_command=([action]="add" [identifier]="test" [x]="0" [y]="0" [path]="/windows/Images/rest/pikachu.jpg"); sleep 1)
```

should display the image for a second.
