### ISSUE TITLE
fzfimg image width

### ISSUE THREAD

**Issue by AckslD** [seebye/ueberzug#132]
When trying out the example `fzfimg` the images seem to be maximised in height which usually makes it so that the full width of the image is not show. Any good ideas on how to always see the whole image?

**Comment by seebye** [comment]
You just need to adjust the add command.  
https://github.com/seebye/ueberzug/blob/master/examples/fzfimg.sh#L110  
https://github.com/seebye/ueberzug#add

**Comment by AckslD** [comment]
Thanks @seebye, setting `scaler=fit_contain` worked great! :)
