### ISSUE TITLE
Cropping images does not seem to work

### ISSUE THREAD

**Issue by AdamTillou** [seebye/ueberzug#140]
I have the following script running Ueberzug,
```
#!/bin/bash
source "`ueberzug library`"

ImageLayer 0< <(
	ImageLayer::add [identifier]="example" [x]="5" [y]="5" [max_width]="20" [max_height]="10" [path]="/home/adam/Pictures/MyImage.png" [crop]="0.5"
	read
)
```
but when I run it I get the error

`[type]=error [name]=TypeError [message]='__init__() got an unexpected keyword argument '"'"'crop'"'"''`

How do I specify the amount to crop the image by?

**Comment by seebye** [comment]
The add action has no "crop" parameter.  

> How do I specify the amount to crop the image by?

The amount is specified by the size of the placement.  
The position is specified by scaling_position_x, scaling_position_y.
