### ISSUE TITLE
Ability to pass PIL.Image object

### ISSUE THREAD

**Issue by shanedabes** [seebye/ueberzug#19]
Would it be possible to implement the ability to pass an image object to the placement? This would allow displaying images from sources like URLs without having to save the image to disk first. Something like:

```
with urllib.request.urlopen(url) as response:
    data = response.read()
img = Image.open(io.BytesIO(data))
with ueberzug.Canvas() as c:
    demo = c.create_placement('demo', x=0, y=0)
    demo.img = img
```

Apologies if this is already possible and I've missed it.

**Comment by seebye** [comment]
> Apologies if this is already possible and I've missed it.

No, you're right that's not possible currently.  

> Would it be possible to implement the ability to pass an image object to the placement?

There are some changes required to do that.  
In the current design of the protocol stdin is only used for instructions.  
The python library provides a placement object which allows to do individual changes,  
but that's not how the protocol works.  
There are only two real commands add and remove,  
so if you add data to the protocol it also needs to be transfered everytime you change something.  
(as each change of a variable transfers a add command if the image is visible)  
So the easiest way to implement it would be to allocate Images objects (transfer e.g. via fifo) in ueberzug and assign it to a pseudo path,  
but I don't really like that as it's a potential source of memory leaks.  
The next way to do it which comes to my mind is by using tmpfs.
On systems with systemd there should be a mounted tmpfs file system in `/run/user/$UID`,  
so you could just store it there to keep it in RAM.  
(this should already work by the way)

**Comment by sharktamer** [comment]
OK, I think I understand (and to be honest I didn't even know about /run/user/$UID and /dev/shm).

One thing that still has me wondering though is the fact that you're creating an Image object anyway in the AddImageAction class. I would have thought that adding another entrypoint that skips the

`image = Image.open(path)`

done on line 122 of action.py

**Comment by seebye** [comment]
> One thing that still has me wondering though is the fact that you're creating an Image object anyway in the AddImageAction class. I would have thought that adding another entrypoint that skips the
> `image = Image.open(path)`
> done on line 122 of action.py

I will likely add a LruCache in the future to avoid loading images multiple times  
and if you just skip the `Image.open` call you still need to transfer the image on each change as the action is defined to replace a existing placement.  
So simply extending the add action would bypass the cache.

**Comment by seebye** [comment]
I decided not to implement this.

Reasons:

- I don't want to mix instructions and normal data.  
  As explained above this would be a bottleneck due to the structure of the protocol.
- I don't want the additional complexity of managing network resources or ram disk or ...
  A program that needs to use network resources should download, cache, .... these images itself.
