### ISSUE TITLE
Wayland compatibility, failure

### ISSUE THREAD

**Issue by krnl0138** [seebye/ueberzug#30]
OS: arch
WM: sway-git
DS: wayland-git
FM: ranger-git

Ueberzug fails as preview tool for ranger in sway. Which is obvious due to different architectures.
The question is will there be a support for wayland? Because ueberzug is great in X.
Log from error output while trying to preview an image:

```
Traceback (most recent call last):
  2   File "/usr/bin/ueberzug", line 11, in <module>
  3     load_entry_point('ueberzug==18', 'console_scripts', 'ueberzug')()
  4   File "/usr/lib/python3.7/site-packages/ueberzug/ueberzug.py", line 225, in main
  5     main_layer(options)
  6   File "/usr/lib/python3.7/site-packages/ueberzug/ueberzug.py", line 175, in main_layer
  7     window_infos = xutil.get_parent_window_infos()
  8   File "/usr/lib/python3.7/site-packages/ueberzug/xutil.py", line 159, in get_parent_window_infos
  9     pid_window_id_map = get_pid_window_id_map()
 10   File "/usr/lib/python3.7/site-packages/ueberzug/xutil.py", line 98, in get_pid_window_id_map
 11     Xlib.X.AnyPropertyType)
 12 AttributeError: 'NoneType' object has no attribute 'value'  
```

**Comment by seebye** [comment]
As far as I know wayland isolates windows from each other, so ueberzug can't work as a wayland client.  

According to https://wayland.freedesktop.org/docs/html/ch05.html X11 clients aren't isolated from each other in Xwayland.  
So you could try to use some terminal emulator with Xwayland.

> A Wayland compositor usually spawns only one Xwayland instance. This is because many X11 applications assume they can communicate with other X11 applications through the X server, and this requires a shared X server instance. This also means that Xwayland does not protect nor isolate X11 clients from each other, unless the Wayland compositor specifically chooses to break the X11 client intercommunications by spawning application specific Xwayland instances. X11 clients are naturally isolated from Wayland clients.

**Comment by pprobst** [comment]
Hello,

For some reason I have the exact same error, even though I'm using X. As it's the same message, I didn't create a new issue.

```
Traceback (most recent call last):
  File "/usr/bin/ueberzug", line 11, in <module>
    load_entry_point('ueberzug==18.1.3', 'console_scripts', 'ueberzug')()
  File "/usr/lib/python3.7/site-packages/ueberzug/ueberzug.py", line 225, in main
    main_layer(options)
  File "/usr/lib/python3.7/site-packages/ueberzug/ueberzug.py", line 175, in main_layer
    window_infos = xutil.get_parent_window_infos()
  File "/usr/lib/python3.7/site-packages/ueberzug/xutil.py", line 159, in get_parent_window_infos
    pid_window_id_map = get_pid_window_id_map()
  File "/usr/lib/python3.7/site-packages/ueberzug/xutil.py", line 98, in get_pid_window_id_map
    Xlib.X.AnyPropertyType)
AttributeError: 'NoneType' object has no attribute 'value'
```
Looking at line 94:
`root = display.screen().root`
`root` is being set to "None" instead of some type of display object. At line 98 the program attempts to grab a specific value from the `root` object and Python crashes since root isn't actually set to anything.

I'm using _st_ and I'm trying to preview images on _vifm_. The same error occurs when I try to preview images manually, outside _vifm_.

**Comment by goetzc** [comment]
@seebye Testing [wdisplays](https://github.com/cyclopsian/wdisplays) I realized it draws over other windows, the protocol is [wlr-screencopy-unstable-v1](https://github.com/swaywm/wlroots/blob/master/protocol/wlr-screencopy-unstable-v1.xml#L26), which is supported by [wlroots](https://github.com/cyclopsian/wdisplays) (used by sway and others), so it looks like ueberzug on Wayland is possible.
