### ISSUE TITLE
Feature request: Scaler option like 'contain' that also resizes smaller images to fit within the desired area

### ISSUE THREAD

**Issue by Ryujinra** [seebye/ueberzug#36]
**EDIT: Implemented this myself in #37. Seems to work perfectly on a number of images, but perhaps you have a more rigorous test set you'd like to run it on before merging.**

`contain` is useful for scaling larger images down while maintaining aspect ratio, but smaller images are not similarly scaled up as much as possible within the bounds of the desired area while maintaining the aspect ratio.

`forced_cover` _does_ resize smaller images while maintaining aspect ratio, but if the ratio doesn't match the desired area, it just clips the image.

I think another scaling option that behaves like `contain` but also resizes a smaller image to fit the desired area while maintaining the aspect ratio would be useful and perhaps should be the default mode, since if a user is supplying a width and height, they probably expect the image to be upscaled/downscaled to that size, without cropping, by default.

Thanks for your consideration.

**Comment by seebye** [comment]
>  perhaps should be the default mode

1. I disagree, if you normally want to display an image you don't want to reduce the image quality by upscaling it.  
2. In previous versions there were only two image scalers distort and contain.  
The distort scaler was used if a value was specified for width or height.  
The contain scaler was used if a value was specified for max_width or max_height.  
I decided to use contain as the default scaler as most people used obviously max_width and max_height.  
And I won't change this as it would break scripts.  

> since if a user is supplying a width and height, they probably expect the image to be upscaled/downscaled to that size, without cropping, by default.

You aren't specifying the width & height of the image you're specifying the width & height of the placement.

**Comment by Ryujinra** [comment]
I guess my initial confusion is that I didn't expect the behavior of width/height to be that of  max_width/max_height, which seemed more representative of what will happen to the image if it is smaller or larger than the placement dimensions.

In any case, I simply added another scaler `max_contain` which downscales larger images to the placement dimensions or upscales smaller images as large as possible without cropping while maintaining their aspect ratio. Maybe `fit` or something similar would be a better name.
