### ISSUE TITLE
Can't get it to display image

### ISSUE THREAD

**Issue by karasuma-chitose** [seebye/ueberzug#39]
When I try to get it to display an image like so for example:
```
echo '{"action": "add", "identifier": "test", "x": 0, "y": 0, "path": "/path/to/my/img.jpg"}' | ueberzug layer
```
I don't get anything. No errors, just nothing.
Is it possible that I have a dependency missing or something?
Tried multiple terminals (urxvt, xterm and mlterm).
w3mimgdisplay works perfectly btw.

**Comment by seebye** [comment]
Duplication of https://github.com/seebye/ueberzug/issues/5
Ueberzug uses it's own window and needs to run as long as the image should be visible.  
You're simply piping the command to ueberzug's stdin so ueberzug closes right away as every other program.

**Comment by karasuma-chitose** [comment]
Wait a sec, I tried using this script as well
```
#!/bin/bash
source "`ueberzug library`"

ImageLayer 0< <(
    ImageLayer::add [identifier]="test" [x]="0" [y]="0" [path]="$1"
    read
)
```
and when calling it like so `imgcat /path/to/my/image.jpg`, all it does is it waits for keyboard input, but it doesn't display the image.
There's no flickering, just nothing.
I also tried running ueberzug like so `ueberzug layer` and giving it `{"action": "add", "identifier": "test", "x": 0, "y": 0, "path": "/path/to/img.jpg"}` and nothing (no error message either).

**Comment by seebye** [comment]
- Which terminal emulator do you use?  
- Does your terminal emulator set the _NET_WM_PID property?  
(That's a requirement)
- Do you use any kind of sandbox e.g. firejail?  
In this case you also need to start your terminal emulator in the sandbox.

**Comment by karasuma-chitose** [comment]
Okay, this is funny. I can't believe I haven't noticed it sooner.
The problem is that I'm using urxvtd. All my terminals have the same PID.
When I run ueberzug, it displays the image on the urxvt client that was opened last for some reason.
I haven't noticed it earlier because it displayed the image on another terminal on another workspace.
The reason it didn't work when I tried it on xterm and mlterm yesterday is because I was using that pipe command.
It wouldn't have worked on mlterm anyway because it doesn't set the _NET_WM_PID property.

**Comment by karasuma-chitose** [comment]
Suppose I'll close the issue since I don't really care if it works with urxvtd or not.
It's not a great idea to use urxvtd anyway.
