### ISSUE TITLE
Images are not displaying. Problems with Xauth?

### ISSUE THREAD

**Issue by tbdcit** [seebye/ueberzug#40]
I am having some trouble displaying images, when trying to display an image using either the example scripts provided or in ranger I receive the following warning repeatedly:

```
Xlib.xauth: warning, no xauthority details available
```

and no image is displayed. 

I am using Arch linux and have tried both the AUR packages `python-ueberzug` and `python-ueberzug-git`. I have tried the following terminals (with and without tmux) each with the same result

 - termite
 - st
 - sakura

Let me know if any other information would be useful.

**Comment by seebye** [comment]
Well, the releated message is printed during setting up the connection to X11.  

https://github.com/python-xlib/python-xlib/blob/master/Xlib/xauth.py#L93
https://github.com/python-xlib/python-xlib/blob/992fe6f669078d60e488f88b093769d754c88e7a/Xlib/support/unix_connect.py#L135
https://github.com/python-xlib/python-xlib/blob/936af08a5378dff9f9a107b902dfe3da3e2fde62/Xlib/protocol/display.py#L91

I can't help you with this issue as it's an issue of python-xlib (or your configuration?).
