### ISSUE TITLE
AttributeError when trying to display image

### ISSUE THREAD

**Issue by pprobst** [seebye/ueberzug#41]
Hello,

For some reason I have the exact same error as shown [here](https://github.com/seebye/ueberzug/issues/30) even though I'm using X.

```
Traceback (most recent call last):
  File "/usr/bin/ueberzug", line 11, in <module>
    load_entry_point('ueberzug==18.1.3', 'console_scripts', 'ueberzug')()
  File "/usr/lib/python3.7/site-packages/ueberzug/ueberzug.py", line 225, in main
    main_layer(options)
  File "/usr/lib/python3.7/site-packages/ueberzug/ueberzug.py", line 175, in main_layer
    window_infos = xutil.get_parent_window_infos()
  File "/usr/lib/python3.7/site-packages/ueberzug/xutil.py", line 159, in get_parent_window_infos
    pid_window_id_map = get_pid_window_id_map()
  File "/usr/lib/python3.7/site-packages/ueberzug/xutil.py", line 98, in get_pid_window_id_map
    Xlib.X.AnyPropertyType)
AttributeError: 'NoneType' object has no attribute 'value'
```
Looking at line 94 of `xutil.py`:
root = display.screen().root
root is being set to "None" instead of some type of display object. At line 98 the program attempts to grab a specific value from the root object and Python crashes since root isn't actually set to anything.

I'm using _st_ and I'm trying to preview images on _vifm._ The same error occurs when I try to preview images manually, outside vifm.

**Comment by seebye** [comment]
root isn't set to None, but your root window seems to miss the '_NET_CLIENT_LIST' property which is currently a requirement.

**Comment by pprobst** [comment]
Thanks, I managed to solve the problem.
To anyone using xmonad: import [XMonad.Hooks.EwmhDesktops](https://hackage.haskell.org/package/xmonad-contrib-0.15/docs/XMonad-Hooks-EwmhDesktops.html).
