### ISSUE TITLE
Images "jump" between instances of Xfce Terminal

### ISSUE THREAD

**Issue by GeorgeHJ** [seebye/ueberzug#43]
Hello,

Thanks for this great project.

I have been playing with it to display album art in a `tmux` session along with `ncmpcpp`.

My problem is that when the image is loaded by `ImageLayer` and another instance of Xfce Terminal is open, the picture jumps to the other terminal.

The same doesn't happen with UXTerm or Alacritty.

Has anyone experienced this? I can share my display script if that would help.

**Comment by seebye** [comment]
Xfce4 terminal seems to use a daemon which handles all windows.  
Ueberzug requires to the terminal to use a process per window so xfce4-terminal isn't supported.  
(The same applies for the daemon mode of urxvt.)
