### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by aybli** [seebye/ueberzug#45]
Hey, when running the bash example script instead of images I get this:
`/usr/lib/python3.7/site-packages/ueberzug/lib/lib.sh: line 41:  5274 Illegal instruction     (core dumped) ueberzug layer -p bash "$@"` (two times and then nothing happens..)

I tried the vifm script you posted on reddit first and that made vifm freeze so I tried this to see if I get any output. The python example script also shows no images and I don't get any output. I'm a new linux user and set up my system using the [LARBS](https://github.com/LukeSmithxyz/LARBS) script and since nobody had any issues with that it seems like it's a hardware issue. I hope I didn't miss anything obvious but I read a lot now and can't find anything that helps.

CPU: Intel Pentium Dual T3200

**Comment by podocarp** [comment]
After trying the script from reddit, I get something similar. vifm freezes and I get this from stderr:
```
 line 1: 22531 Broken pipe             tail --follow "$FIFO_UEBERZUG"
 22532 Segmentation fault      | ueberzug layer --silent --parser bash
```

**Comment by podocarp** [comment]
I have done some testing. Apparently it works just fine with version 18 but not >18.1. This is odd.

**Comment by podocarp** [comment]
I got it working by installing pillow beside pillow-simd.

**Comment by aybli** [comment]
>I got it working by installing pillow beside pillow-simd.

@podocarp That made it work for me too! Thank you!
