### ISSUE TITLE
Build fails on OpenBSD 6.5

### ISSUE THREAD

**Issue by dmimms** [seebye/ueberzug#48]
X11/Xlib.h on OpenBSD is located at /usr/X11R6/include/X11/Xlib.h

Here are the last several lines from the pip3 install:
```
    reading manifest file 'ueberzug.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'ueberzug.egg-info/SOURCES.txt'
    copying ueberzug/lib/lib.sh -> build/lib.openbsd-6.5-amd64-3.7/ueberzug/lib
    running build_ext
    building 'Xshm' extension
    creating build/temp.openbsd-6.5-amd64-3.7
    creating build/temp.openbsd-6.5-amd64-3.7/Xshm
    cc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fPIC -O2 -pipe -O2 -pipe -fPIC -I/usr/local/include/python3.7m -c Xshm/Xshm.c -o build/temp.openbsd-6.5-amd64-3.7/Xshm/Xshm.o
    Xshm/Xshm.c:5:10: fatal error: 'X11/Xlib.h' file not found
    #include <X11/Xlib.h>
             ^~~~~~~~~~~~
    1 error generated.
    error: command 'cc' failed with exit status 1

    ----------------------------------------
Command "/usr/local/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ixesyci4/ueberzug/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-98gl_gwz-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ixesyci4/ueberzug/
```

**Comment by seebye** [comment]
You need to install the dev packages of X11, e.g. libx11-dev on debian.  
Xext is also required to build the c module.  
However I'm not sure whether psutil (a dependency of this project) supports bsd.  
https://github.com/seebye/ueberzug/issues/44

**Comment by marvinborner** [comment]
Actually this isn't the reason the command failed @seebye (libx11 is pre-installed on OpenBSD)

The actual solution is offered in https://stackoverflow.com/a/19253719 as OpenBSD stores their X11 Libraries in a different place than Python expects them to be. Therefore adding  

> [build_ext]
> include_dirs=/usr/X11R6/include
> library_dirs=/usr/X11R6/lib

to `~/.pydistutils.cfg` should solve the problem (at least it fixed it on my fresh OpenBSD installation)
