### ISSUE TITLE
does ueberzug work with w3m web browser?

### ISSUE THREAD

**Issue by gotbletu** [seebye/ueberzug#53]
is it possible to get ueberzug to work in w3m web browser?

usually with **w3mimgdisplay** i can browse with image fine using:

`w3m -o display_image=1 -o imgdisplay=w3mimgdisplay google.com`

but when i try with **ueberzug** it does nothing:

```
w3m -o display_image=1 -o imgdisplay=ueberzug google.com

w3m -o display_image=1 -o imgdisplay=/usr/bin/ueberzug google.com

```

**Comment by seebye** [comment]
No, it doesn't.  
There are a few issues if you would want to use ueberzug with w3m:  

- ueberzug and w3mimgdisplay use different command formats
- ueberzug uses characters / terminal cells as size unit  while w3mimgdisplay uses pixels

So you can't just tell w3m to use ueberzug you need to create a script which accepts w3mimgdisplay commands and sends ueberzug commands.
