### ISSUE TITLE
Alternative to using ImageLayer 'sleep'

### ISSUE THREAD

**Issue by vredesbyyrd** [seebye/ueberzug#54]
Hi, thanks for creating this great tool.

I am trying to use Ueberzug with fzf to display images in its [preview](https://github.com/junegunn/fzf#preview-window) pane. This is all in [tilda](https://github.com/lanoxx/tilda) terminal. When fzf gets run, it calls this script to display info in the preview pane: 

```
#!/bin/bash

if [[ "$1" == *.@(flac|mp3|mp4|m4a) ]]; then
    echo | mediainfo --inform "$1"
fi

if [[ "$1" == *.@(jpg|jpeg|png) ]]; then
    echo "$1"

source "`ueberzug library`"

ImageLayer 0< <(
   ImageLayer::add [identifier]="previewImage" [x]="0" [y]="25" [width]="50" [height]="45" [path]="$1"
   sleep 100d
)
fi
exit 0
```

The image only displays as long as the sleep period so I currently have it set indefinitely. The issue is, for the first image displayed its filename never gets properly echo'd. With any subsequent previews it will display the filename but from the _prior_ match. This could probably be better communicated with a screenshot: 

![Screenshot from 2019-06-16 21-54-46](https://user-images.githubusercontent.com/22080838/59575569-a9797100-9081-11e9-9545-d6b11f36209f.png)

The displayed image is _misc_21.jpg_ , but the filename printed is from the previous match _misc_30.jpg_ . This happens regardless of the file-type being previewed. When fzf initially calls the script the  `ImageLayer 0< <(` _sleep_ command is preventing the filename from being properly echo'd. 

I know this is not necessarily an issue with ueberzug, probably more a reflection of my s**t programming, so my question is a general one. Is there anyway around sleeping `ImageLayer::add` to get  the image to display? I have tried using `read` as shown in the bash examples but the image will just flash momentarily. The `synchronous_lazy_drawing` property sounds like it might be helpful here but I am unsure how to implement it. Lastly, I have tried a handful of different things programmatically like forking the ImageLayer / sleep command so that the rest of the script can continue to run, but no dice. 

Überzug + fzf's preview pane would be a killer combo. But as I am sure is evident from above I am not much of a programmer. If you have any thoughts on how to get around this I would love to hear them!  

Thank you for your time.

**Comment by seebye** [comment]
I'm using fzf &mpc as music player, covers are shown by using ueberzug.  
See: https://github.com/seebye/fmui https://github.com/seebye/fmui/blob/master/cover.sh  

Ueberzug displays images only as long as it runs,  
so you need to change your approach.  
Instead of running ueberzug as preview command you should start ueberzug before fzf and kill it after fzf exits.  
```bash
#!/usr/bin/env bash
readonly BINARY_BASH="$(which bash)"
declare -r -x UEBERZUG_FIFO="$(mktemp --dry-run --suffix ueberzug)"
declare -r -x PREVIEW_ID="preview"
declare -r -x PREVIEW_WIDTH=30


function start_ueberzug {
    mkfifo "$UEBERZUG_FIFO"
    ueberzug layer --parser bash --silent <"$UEBERZUG_FIFO" &
    # prevent EOF
    exec 3>"$UEBERZUG_FIFO"
}


function stop_ueberzug {
    exec 3>&-
    rm "$UEBERZUG_FIFO" &>/dev/null
}


function get_mime_type {
    file --brief --mime-type "$@"
}


function on_selection_changed {
    if [[ "$(get_mime_type "$@")" == "image/"* ]]; then
        >"${UEBERZUG_FIFO}" declare -A -p cmd=( \
            [action]=add [identifier]="${PREVIEW_ID}" \
            [x]=1 [y]=1 [width]="${PREVIEW_WIDTH}" [height]="$(($(tput lines) - 2))" \
            [path]="$@")
    else
        >"${UEBERZUG_FIFO}" declare -A -p cmd=( \
            [action]=remove [identifier]="${PREVIEW_ID}" )
    fi
}


if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    export -f get_mime_type on_selection_changed
    trap stop_ueberzug EXIT
    start_ueberzug

    SHELL="$BINARY_BASH" \
        fzf --preview "on_selection_changed {}" \
            --preview-window "left:${PREVIEW_WIDTH}"
fi
```

**Comment by vredesbyyrd** [comment]
> Instead of running ueberzug as preview command you should start ueberzug before fzf and kill it after fzf exits.

I cannot thank you enough! This approach works so much better. There is zero delay in loading images which is very impressive. Ill have dig into this a little further tomorrow to fully understand how this works. 

I very much appreciate you writing this up. I am sure it will come in as a handy reference for others as well. 

Cheers.

**Comment by seebye** [comment]
In case you're interested in it:  
I extended the script to also support previews on the top, bottom, left & right side.  
Also I added a hack to force fzf to recreate the preview on resizing the terminal window.

https://github.com/seebye/ueberzug/blob/master/examples/fzfimg.sh

**Comment by vredesbyyrd** [comment]
> Also I added a hack to force fzf to recreate the preview on resizing the terminal window.

Thanks for the heads up. I am definitely interested in this aspect. When time abides Ill implement it into my script and test it out. Cheers!
