### ISSUE TITLE
Ueberzug segfaults when scaling image

### ISSUE THREAD

**Issue by jstkdng** [seebye/ueberzug#56]
When using ueberzug layer, trying to scale down a large image segfaults. This is more noticeable in ranger because it won't show image previews because of this.
Using this image for example, and using ranger values:
```json
{"action": "add", "identifier": "preview", "x": 118, "y": 2, "width": 118, "height": 60, "scaler": "cover", "path": "..."}
```
![D7hvKmCVUAAcVjl](https://user-images.githubusercontent.com/52050345/60225020-99fce380-984a-11e9-8cbe-f593794fccf8.jpeg)
Weirdly enough, for another large image, it will actually show it only if the terminal windows is smaller (?)
Test image and same values before:
![abf](https://user-images.githubusercontent.com/52050345/60225067-cb75af00-984a-11e9-8178-35c7593b9c58.jpg)
![image](https://user-images.githubusercontent.com/52050345/60225081-e21c0600-984a-11e9-871c-5124017e15f6.png)
Once I resize the terminal window to its original size, ueberzug segfaults.

Using another scale method doesn't help either:
![image](https://user-images.githubusercontent.com/52050345/60225189-522a8c00-984b-11e9-8951-1303115b50b6.png)

**Comment by seebye** [comment]
Did you already tried to replace pillow-simd with pillow? See: https://github.com/seebye/ueberzug/issues/45

```bash
$ sudo pip uninstall pillow-simd
$ sudo pip install pillow
```

**Comment by jstkdng** [comment]
I'm getting this error now when starting ueberzug
```
Traceback (most recent call last):
  File "/usr/bin/ueberzug", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pillow-simd' distribution was not found and is required by ueberzug
```

**Comment by seebye** [comment]
That's an issue of the way you installed it, e.g. if I remove any dependency I get an expected import error.  
Although I don't know how to order pip to install it without doing this, that just seems to be the default setting on debian.  

You can try to 
1. install ueberzug without dependecies
2. install the required dependencies
(I don't know whether it will also check whether the declared packages are installed or not.
(Like it did in your stacktrace))
```bash
$ sudo pip uninstall ueberzug
$ #  install ueberzug without dependencies
$ sudo pip install --no-deps ueberzug
$ # Installing the dependencies except pillow-simd
$ sudo pip install python-xlib docopt psutil attrs pillow
```

If that also won't work you can try to install it from source,
but in this case I would install it in a virtualenv as it's a pain to uninstall it.
```bash
$ git clone https://github.com/seebye/ueberzug
$ cd ueberzug
$ vim setup.py # replace pillow-simd with pillow
$ python -m virtuelenv venv
$ source venv/bin/activate
$ ./setup.py install
$ { declare -A -p c=([action]="add" [identifier]="preview" [x]=118 [y]=2 [width]=118 [height]=60 [scaler]="cover" [path]="..."); read; } | ueberzug layer --parser bash
```

**Comment by jstkdng** [comment]
Can confirm now, using normal pillow works as expected. Thanks @seebye , also, I think my problem is that I'm using this aur package: https://aur.archlinux.org/packages/python-ueberzug-git/ and it shows pillow-simd as one of its dependencies, I'll try to contact the maintainer or maybe I'll just create another package. Or maybe it is a problem with pillow-simd itself, is it working for you @seebye ?

![image](https://user-images.githubusercontent.com/52050345/60304123-0be23500-98fe-11e9-9470-004d6ebfb0e4.png)

**Comment by seebye** [comment]
>  Or maybe it is a problem with pillow-simd itself, is it working for you @seebye ?

Yes, pillow-simd works for me without any problem since months.

**Comment by jstkdng** [comment]
yeah, it seems it is a problem with pillow-simd on my end, I'll start the discussion over there.
![image](https://user-images.githubusercontent.com/52050345/60305928-f3751900-9903-11e9-80a6-bb57422b60da.png)
thanks for the help @seebye.
