### ISSUE TITLE
FreeBSD Installation via pip Problem

### ISSUE THREAD

**Issue by rusmelezi** [seebye/ueberzug#60]
I wanted to test Überzug with FreeBSD today and tried to install it via pip. 

This is output.

 copying ueberzug/ui.py -> build/lib.freebsd-12.0-STABLE-amd64-3.6/ueberzug
    copying ueberzug/xutil.py -> build/lib.freebsd-12.0-STABLE-amd64-3.6/ueberzug
    creating build/lib.freebsd-12.0-STABLE-amd64-3.6/ueberzug/lib
    copying ueberzug/lib/__init__.py -> build/lib.freebsd-12.0-STABLE-amd64-3.6/ueberzug/lib
    creating build/lib.freebsd-12.0-STABLE-amd64-3.6/ueberzug/lib/v0
    copying ueberzug/lib/v0/__init__.py -> build/lib.freebsd-12.0-STABLE-amd64-3.6/ueberzug/lib/v0
    running egg_info
    writing ueberzug.egg-info/PKG-INFO
    writing dependency_links to ueberzug.egg-info/dependency_links.txt
    writing entry points to ueberzug.egg-info/entry_points.txt
    writing requirements to ueberzug.egg-info/requires.txt
    writing top-level names to ueberzug.egg-info/top_level.txt
    reading manifest file 'ueberzug.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'ueberzug.egg-info/SOURCES.txt'
    copying ueberzug/lib/lib.sh -> build/lib.freebsd-12.0-STABLE-amd64-3.6/ueberzug/lib
    running build_ext
    building 'Xshm' extension
    creating build/temp.freebsd-12.0-STABLE-amd64-3.6
    creating build/temp.freebsd-12.0-STABLE-amd64-3.6/Xshm
    cc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -fPIC -I/usr/local/include/python3.6m -c Xshm/Xshm.c -o build/temp.freebsd-12.0-STABLE-amd64-3.6/Xshm/Xshm.o
    Xshm/Xshm.c:5:10: fatal error: 'X11/Xlib.h' file not found
    #include <X11/Xlib.h>
             ^~~~~~~~~~~~
    1 error generated.
    error: command 'cc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/usr/local/bin/python3.6 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-kzlvj498/ueberzug/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-yfp81nyi/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-kzlvj498/ueberzug/

**Comment by rusmelezi** [comment]
It must look to /usr/include and /usr/lib for libs and headers for BSD systems. But apearantly it is not doing it. fatal error: 'X11/Xlib.h' file not found

**Comment by seebye** [comment]
There's already an issue about this subject: https://github.com/seebye/ueberzug/issues/48
