### ISSUE TITLE
How to install in MacOS?

### ISSUE THREAD

**Issue by chris-kahn** [seebye/ueberzug#61]
I have XQuartz installed and I ran `ln -s /opt/X11/include/X11 /usr/local/include/X11`, but I still get errors when trying to install via pip3: 

```
clang -bundle -undefined dynamic_lookup build/temp.macosx-10.14-x86_64-3.7/Xshm/Xshm.o -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -lX11 -lXext -o build/lib.macosx-10.14-x86_64-3.7/Xshm.cpython-37m-darwin.so
    ld: library not found for -lX11
```

**Comment by seebye** [comment]
I don't support MacOS, so you need to look it up yourself.  
Also I can't say whether ueberzug works on MacOS I don't really care if it runs on anything else than Linux.  

All the message says is that there are some dev files missing / not at the expected place.  
The **direct** dependencies of the c code of ueberzug are listed here: https://github.com/seebye/ueberzug#dependencies

**Comment by XO39** [comment]
@chris-kahn [This solution](https://stackoverflow.com/a/19253719/587990) worked for me. In short:
Adding
```
[build_ext]
include_dirs=/usr/X11R6/include
library_dirs=/usr/X11R6/lib
```
to  `~/.pydistutils.cfg` should fix this problem.

**Comment by glepnir** [comment]
Thanks . i got it work
![image](https://user-images.githubusercontent.com/41671631/85938502-8b0aae80-b940-11ea-937c-1f0e8890ead1.png)

**Comment by adelarsq** [comment]
For me was possible to install using:
```
[build_ext]
include_dirs=/opt/X11/include
library_dirs=/opt/X11/lib
```
on the `~/.pydistutils.cfg` file.

**Comment by Mathijs-Bakker** [comment]
> For me was possible to install using:
> 
> ```
> [build_ext]
> include_dirs=/opt/X11/include
> library_dirs=/opt/X11/lib
> ```
> 
> on the `~/.pydistutils.cfg` file.

**Affirmative!**

After installing [X11 from the XQuartz website](https://www.xquartz.org) and adding the **~/.pydistutils.cfg** (as mentioned above) to the $HOME folder. Solves the building issue for MacOS.

Thanks!

**Comment by glepnir** [comment]
Does anyone can use it on macosx?  Ueberzug install successful on my mac. but I can't use it.

**Comment by Mathijs-Bakker** [comment]
> Does anyone can use it on macosx? Ueberzug install successful on my mac. but I can't use it.

I wanted to use Überzug as an image previewer for [Ranger](https://github.com/ranger/ranger).
But neither did I got that to work. I did spend too much time to solve it so I walked away.

**Comment by adelarsq** [comment]
Me too. Was able to install but can't use. Still didn't have time to see why.

**Comment by seebye** [comment]
I decided to lock this issue after reading apple's restrictive practices regarding running unsigned software.  
https://news.ycombinator.com/item?id=24217116
https://lapcatsoftware.com/articles/unsigned.html
I don't want my software to run on such systems.
