### ISSUE TITLE
Should consider `pip install --user` rather than `sudo pip install`

### ISSUE THREAD

**Issue by jordannewport** [seebye/ueberzug#66]
Is there a reason you use `sudo pip install` rather than `pip install --user` in the installation instructions?

Using `pip install --user` can reduce the risk of security vulnerabilities and additionally avoids polluting the global namespace. See more discussion of the disadvantages of `sudo pip` here: https://stackoverflow.com/questions/21055859/what-are-the-risks-of-running-sudo-pip and in some of the linked questions as well.

**Comment by seebye** [comment]
There's no reason to use sudo.  
ueberzug doesn't use root rights or something like that.  
So it's not a problem to install it for a single user only.
