### ISSUE TITLE
lxterminal display image in multiple tabs

### ISSUE THREAD

**Issue by pvpscript** [seebye/ueberzug#73]
I'm on Debian 10 Buster, using `lxterminal 0.3.2` and if I display an image in one tab, when I switch tabs the image won't go away unless I stop displaying it in the original tab.

Edit: The same problem occurs on` xfce4-terminal`
![image](https://user-images.githubusercontent.com/33137099/64492687-05046680-d24d-11e9-9d77-248b33c6b99c.png)
![image](https://user-images.githubusercontent.com/33137099/64492693-1baabd80-d24d-11e9-9a81-8a7a353ccfd6.png)

**Comment by seebye** [comment]
Ueberzug doesn't (and never will) support terminal features like tabs.  
Use tmux if you want to use tabs (tmux windows).
