### ISSUE TITLE
Adding pywal execution comand

### ISSUE THREAD

**Issue by annata83** [seebye/ueberzug#76]
Hi There Again.
I have no idea how to go about this. All I would like to do is to execute a command in a image I am standing at with pywal like so:

`wal -i $1 -st && cp $1 ~/.config/wall.png`

can I ask you for instructions on were do I add this command inside the script to set the current selected image as wallpaper and after it executes re-execute the fzfuimg script again ether to exit after or pick another images?

**Comment by seebye** [comment]
You can pass the fzf arguments to fzfimg.sh:

```bash
fzfimg.sh --bind 'enter:execute-silent(wal -i {})'
```

**Comment by annata83** [comment]
Thank; Works Perfectly!.
Do you mind leaving an explanation for further understanding under the hood of it.

If not and I understand you have a lot to do Thank you very much anyway!.

**Comment by seebye** [comment]
> Do you mind leaving an explanation for further understanding under the hood of it.

fzfimg.sh just passes the arguments it's called with to fzf.
So the explanation is the fzf man page: https://www.mankier.com/1/fzf#Key_Bindings
