### ISSUE TITLE
Core Dump when try using ueberzug

### ISSUE THREAD

**Issue by Cyberdr3am** [seebye/ueberzug#77]
Hi,

When i try to use ueberzug i have got this error on the journalctl

( I use ueberzug from manjaro repo )

Thx for help

`Process 14511 (ueberzug) of user 1000 dumped core.
                                                        
                                                        Stack trace of thread 14511:
                                                        #0  0x00007f44345577f6 memory_get_block (_imaging.cpython-37m-x86_64-linux-gnu.so)
                                                        #1  0x00007f4434557aab ImagingAllocateArray (_imaging.cpython-37m-x86_64-linux-gnu.so)
                                                        #2  0x00007f4434557c53 ImagingNewInternal (_imaging.cpython-37m-x86_64-linux-gnu.so)
                                                        #3  0x00007f443452d99a n/a (_imaging.cpython-37m-x86_64-linux-gnu.so)
                                                        #4  0x00007f443606c55f _PyMethodDef_RawFastCallKeywords (libpython3.7m.so.1.0)
                                                        #5  0x00007f443606c694 _PyCFunction_FastCallKeywords (libpython3.7m.so.1.0)
                                                        #6  0x00007f443609e933 n/a (libpython3.7m.so.1.0)
                                                        #7  0x00007f44360da222 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                        #8  0x00007f443608c888 _PyEval_EvalCodeWithName (libpython3.7m.so.1.0)
                                                        #9  0x00007f443608da53 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                                                        #10 0x00007f443609e820 n/a (libpython3.7m.so.1.0)
                                                        #11 0x00007f44360da222 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                        #12 0x00007f443608d8b3 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                                                        #13 0x00007f443609e820 n/a (libpython3.7m.so.1.0)
                                                        #14 0x00007f44360d5cfd _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                        #15 0x00007f443608c888 _PyEval_EvalCodeWithName (libpython3.7m.so.1.0)
                                                        #16 0x00007f443608d7aa PyEval_EvalCodeEx (libpython3.7m.so.1.0)
                                                        #17 0x00007f44361220fc PyEval_EvalCode (libpython3.7m.so.1.0)
                                                        #18 0x00007f443616beda n/a (libpython3.7m.so.1.0)
                                                        #19 0x00007f443606c035 _PyMethodDef_RawFastCallDict (libpython3.7m.so.1.0)
                                                        #20 0x00007f443606c194 _PyCFunction_FastCallDict (libpython3.7m.so.1.0)
                                                        #21 0x00007f44360db390 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                        #22 0x00007f443608c888 _PyEval_EvalCodeWithName (libpython3.7m.so.1.0)
                                                        #23 0x00007f443608da53 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                                                        #24 0x00007f443609e820 n/a (libpython3.7m.so.1.0)
                                                        #25 0x00007f44360da222 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                        #26 0x00007f443608d8b3 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                                                        #27 0x00007f443609e820 n/a (libpython3.7m.so.1.0)
                                                        #28 0x00007f44360d5d95 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                        #29 0x00007f443608d8b3 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                                                        #30 0x00007f443609e820 n/a (libpython3.7m.so.1.0)
                                                        #31 0x00007f44360d5cfd _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                        #32 0x00007f443608d8b3 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                                                        #33 0x00007f443609e820 n/a (libpython3.7m.so.1.0)
                                                        #34 0x00007f44360d5cfd _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                        #35 0x00007f443608df2b _PyFunction_FastCallDict (libpython3.7m.so.1.0)
                                                        #36 0x00007f443606b270 n/a (libpython3.7m.so.1.0)
                                                        #37 0x00007f443608943a _PyObject_CallMethodIdObjArgs (libpython3.7m.so.1.0)
                                                        #38 0x00007f44360b6aa4 PyImport_ImportModuleLevelObject (libpython3.7m.so.1.0)
                                                        #39 0x00007f44360b7216 n/a (libpython3.7m.so.1.0)
                                                        #40 0x00007f443606c598 _PyMethodDef_RawFastCallKeywords (libpython3.7m.so.1.0)
                                                        #41 0x00007f443606c694 _PyCFunction_FastCallKeywords (libpython3.7m.so.1.0)
                                                        #42 0x00007f443609e933 n/a (libpython3.7m.so.1.0)
                                                        #43 0x00007f44360d5cfd _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                        #44 0x00007f443608d8b3 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                                                        #45 0x00007f443609e820 n/a (libpython3.7m.so.1.0)
                                                        #46 0x00007f44360d5cfd _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                        #47 0x00007f443608c888 _PyEval_EvalCodeWithName (libpython3.7m.so.1.0)
                                                        #48 0x00007f443608da53 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                                                        #49 0x00007f443609e820 n/a (libpython3.7m.so.1.0)
                                                        #50 0x00007f44360da222 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                        #51 0x00007f443608d8b3 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                                                        #52 0x00007f443609e820 n/a (libpython3.7m.so.1.0)
                                                        #53 0x00007f44360da222 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                        #54 0x00007f443609e1a1 _PyGen_Send (libpython3.7m.so.1.0)
                                                        #55 0x00007f44360d6e81 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                        #56 0x00007f443609e1a1 _PyGen_Send (libpython3.7m.so.1.0)
                                                        #57 0x00007f4435290eae n/a (_asyncio.cpython-37m-x86_64-linux-gnu.so)
                                                        #58 0x00007f443609d93c _PyObject_FastCallKeywords (libpython3.7m.so.1.0)
                                                        #59 0x00007f4436132e79 n/a (libpython3.7m.so.1.0)
                                                        #60 0x00007f443606bee4 _PyMethodDef_RawFastCallDict (libpython3.7m.so.1.0)
                                                        #61 0x00007f443606c194 _PyCFunction_FastCallDict (libpython3.7m.so.1.0)
                                                        #62 0x00007f44360db390 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                        #63 0x00007f443608d8b3 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                                                        
                                                        Stack trace of thread 14531:
                                                        #0  0x00007f44363ade7b __select (libc.so.6)
                                                        #1  0x00007f44364aefcc n/a (select.cpython-37m-x86_64-linux-gnu.so)
                                                        #2  0x00007f443606c55f _PyMethodDef_RawFastCallKeywords (libpython3.7m.so.1.0)
                                                        #3  0x00007f443606c694 _PyCFunction_FastCallKeywords (libpython3.7m.so.1.0)
                                                        #4  0x00007f443609e933 n/a (libpython3.7m.so.1.0)
                                                        #5  0x00007f44360da222 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                        #6  0x00007f443608c888 _PyEval_EvalCodeWithName (libpython3.7m.so.1.0)
                                                        #7  0x00007f443608da53 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                                                        #8  0x00007f443609e820 n/a (libpython3.7m.so.1.0)
                                                        #9  0x00007f44360d6970 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                        #10 0x00007f443608d8b3 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                                                        #11 0x00007f443609e820 n/a (libpython3.7m.so.1.0)
                                                        #12 0x00007f44360d5d95 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                        #13 0x00007f443608df2b _PyFunction_FastCallDict (libpython3.7m.so.1.0)
                                                        #14 0x00007f4436061ab8 _PyObject_Call_Prepend (libpython3.7m.so.1.0)
                                                        #15 0x00007f443608e63e PyObject_Call (libpython3.7m.so.1.0)
                                                        #16 0x00007f44360d727e _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                        #17 0x00007f443608d8b3 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                                                        #18 0x00007f443609e820 n/a (libpython3.7m.so.1.0)
                                                        #19 0x00007f44360d5d95 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                        #20 0x00007f443608df2b _PyFunction_FastCallDict (libpython3.7m.so.1.0)
                                                        #21 0x00007f44360d727e _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                        #22 0x00007f443608d8b3 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                                                        #23 0x00007f443609e820 n/a (libpython3.7m.so.1.0)
                                                        #24 0x00007f44360d5d95 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                        #25 0x00007f443608d8b3 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                                                        #26 0x00007f443609e820 n/a (libpython3.7m.so.1.0)
                                                        #18 0x00007f443609e820 n/a (libpython3.7m.so.1.0)
                                                        #19 0x00007f44360d5d95 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                        #20 0x00007f443608df2b _PyFunction_FastCallDict (libpython3.7m.so.1.0)
                                                        #21 0x00007f44360d727e _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                        #22 0x00007f443608d8b3 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                                                        #23 0x00007f443609e820 n/a (libpython3.7m.so.1.0)
                                                        #24 0x00007f44360d5d95 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                        #25 0x00007f443608d8b3 _PyFunction_FastCallKeywords (libpython3.7m.so.1.0)
                                                        #26 0x00007f443609e820 n/a (libpython3.7m.so.1.0)
                                                        #27 0x00007f44360d5d95 _PyEval_EvalFrameDefault (libpython3.7m.so.1.0)
                                                        #28 0x00007f443608df2b _PyFunction_FastCallDict (libpython3.7m.so.1.0)
                                                        #29 0x00007f4436061ab8 _PyObject_Call_Prepend (libpython3.7m.so.1.0)
                                                        #30 0x00007f443608e63e PyObject_Call (libpython3.7m.so.1.0)
                                                        #31 0x00007f443617598a n/a (libpython3.7m.so.1.0)
                                                        #32 0x00007f44360e6ad5 n/a (libpython3.7m.so.1.0)
                                                        #33 0x00007f4435f5a4cf start_thread (libpthread.so.0)
                                                        #34 0x00007f44363b62d3 __clone (libc.so.6)`

**Comment by seebye** [comment]
This is likely a duplicate of 
https://github.com/seebye/ueberzug/issues/56, https://github.com/seebye/ueberzug/issues/57, https://github.com/seebye/ueberzug/issues/46, https://github.com/seebye/ueberzug/issues/45  

The manjaro community repository contains a old version of ueberzug according to https://repology.org/project/python:ueberzug/versions.  
So there are two options:  
1. Either install ueberzug by using pip if it still crashes make sure that you use pillow instead of pillow-simd.  
2. You could test whether it's still crashes after replacing pillow-simd with pillow-simd compiled with gcc 8.3.0 (See: https://github.com/uploadcare/pillow-simd/issues/53#issuecomment-508328182 )

**Comment by Cyberdr3am** [comment]
Thx for your help.

After install with pip and go with pillow all work nice.
Thx for your help.
