### ISSUE TITLE
running ueberzug on terminal

### ISSUE THREAD

**Issue by hisacro** [seebye/ueberzug#86]
I couldn't find a way to use ueberzug directly on terminal, a better wiki is much appreciated (or I'm missing something?)
I try `ueberzug layer <path to image>`

**Comment by seebye** [comment]
Ueberzug is a daemon program, so images will only be displayed as long as ueberzug runs.  
So if you want to permanently display images in your terminal you need to
1. execute ueberzug as background process and
2. find a way to send commands to ueberzugs stdin

If you want images to move with the (output) text you would have to write something like tmux which updates the images positions.

**Comment by hisacro** [comment]
fair enough, btw it's working great with ranger.
