### ISSUE TITLE
ueberzug does not work with VcxSrv in WSL2 (Windows)

### ISSUE THREAD

**Issue by jantari** [seebye/ueberzug#87]
Hi.

For fun I tried to get ueberzug to work on the Windows Subsystem for Linux (v2).

I tried with the following script (let me know if it's wrong):
```bash
#!/bin/bash
source "`ueberzug library`"

ImageLayer 0< <(
  ImageLayer::add [identifier]="test" [x]="20" [y]="20" [path]="/mnt/d/shutterstock_129316358.jpg"
  read
)
```

however, I get the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/ueberzug", line 11, in <module>
    load_entry_point('ueberzug==18.1.5', 'console_scripts', 'ueberzug')()
  File "/usr/local/lib/python3.6/dist-packages/ueberzug/__main__.py", line 52, in main
    module.main(options)
  File "/usr/local/lib/python3.6/dist-packages/ueberzug/layer.py", line 188, in main
    window_infos = xutil.get_parent_window_infos()
  File "/usr/local/lib/python3.6/dist-packages/ueberzug/xutil.py", line 159, in get_parent_window_infos
    pid_window_id_map = get_pid_window_id_map()
  File "/usr/local/lib/python3.6/dist-packages/ueberzug/xutil.py", line 98, in get_pid_window_id_map
    Xlib.X.AnyPropertyType)
AttributeError: 'NoneType' object has no attribute 'value'
```

I am using ueberzug version `18.1.5` (latest) and have upgraded all pip3 packages to the latest available after having another problem with an outdated `attrs` first, but it did not help.

I am running on Windows 10 Version 10.0.19559.1000, Ubuntu 18.04.4 LTS inside WSL2 on Linux kernel 4.19.84-microsoft-standard. If you need further information please let me know.

I have tried in the native Windows terminal as well as in `xfce4-terminal`. Both produce the same error. I have attached a screenshot of the setup, with the windows terminal in the front, xfce4-terminal in the back and xcalc off to the side for good measure.

![grafik](https://user-images.githubusercontent.com/25607767/74366586-92398180-4dd0-11ea-8606-ca16031a1af2.png)

I hope this can be fixed. It would be great to use ueberzug in WSL on Windows.

It looks like this: https://github.com/nbedos/termtosvg/issues/2 might be a similar issue? The author was able to fix that one. Thanks in advance!

**Comment by seebye** [comment]
I don't intend to support windows.
