### ISSUE TITLE
A video tutorial for fzf integration.

### ISSUE THREAD

**Issue by linxed** [seebye/ueberzug#88]
I learned about your project from Luke Smith and Distro Tube.

Do you think you could record a video tutorial how to integrate ubezug with fzf's preview option ?

**Comment by seebye** [comment]
I'm not going to make a video.  
You can use https://github.com/seebye/fzf-ueberzogen, just install it with `pip install --user fzf-ueberzogen` or `sudo pip install fzf-ueberzogen`.  
Afterwards a shell script should be executeable called fzf-ueberzogen.sh
It accepts the same command line options / flags as fzf does.
The following code shows you the _simplest_ way to use it:

```bash
#!/usr/bin/env bash
function CREATE_PREVIEW {
    # remove the displayed image by calling:
    # CLEAR_PREVIEW
    # (note this is only necessary if you wan't to display text instead of an image)
    
    DRAW_PREVIEW "/path/to/some/image"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    export -f CREATE_PREVIEW
    exec fzf-ueberzogen.sh --preview 'CREATE_PREVIEW {}' "$@"
    # if you need to clean up temporary files with the trap command you should use
    # fzf-ueberzogen.sh --preview 'CREATE_PREVIEW {}' "$@"
    # instead of exec fzf-ueberzogen.sh --preview 'CREATE_PREVIEW {}' "$@"
fi
```
