### ISSUE TITLE
Updated description or add command line examples

### ISSUE THREAD

**Issue by vonbraun1969** [seebye/ueberzug#89]
I was searching for a less buggy way to view images in my terminal than w3m, and when I mentioned that I hated how fim ate your whole screen without screenbuffer shenanigans I was directed here.

The project description is "an alternative for w3mimgdisplay" but I don't think that's accurate.

You mentioned in a request for better documentation that this is expliicitly a daemon that needs to be run in some other way than just "w3m /directory/testing.png"

Are there any other TUIs that use this daemon at the moment?

Could you please provide another example of what it looks like to just enter in a bash command and view an image?

**Comment by seebye** [comment]
> The project description is "an alternative for w3mimgdisplay" but I don't think that's accurate.

It is. w3mimgdisplay is used by some programs to display images as an addition to their tui e.g.  ranger does this and this is what ueberzug is an replacement for.  
Of course it isn't a replacement which can be used with w3m as I have no interest at all in w3m.

> You mentioned in a request for better documentation that this is expliicitly a daemon that needs to be run in some other way than just "w3m /directory/testing.png"

w3m isn't w3mimgdisplay - also I wouldn't care as an alternative doesn't need to work identical to the thing it is an alternative for.  
It just needs to be able to get the same tasks done.  
w3mimgdisplay displays images on terminal emulators in X11 and the same does ueberzug
(of course it's not an alternative if you want to display them in a tty).
