### ISSUE TITLE
Fails to build on FreeBSD

### ISSUE THREAD

**Issue by plasmoduck** [seebye/ueberzug#95]
Running setup.py install for ueberzug ... error
    ERROR: Complete output from command /usr/local/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-ddm1lz4k/ueberzug/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2owdhoog/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.freebsd-12.1-RELEASE-p3-amd64-3.7
    creating build/lib.freebsd-12.1-RELEASE-p3-amd64-3.7/ueberzug
    copying ueberzug/conversion.py -> build/lib.freebsd-12.1-RELEASE-p3-amd64-3.7/ueberzug
    copying ueberzug/__init__.py -> build/lib.freebsd-12.1-RELEASE-p3-amd64-3.7/ueberzug
    copying ueberzug/files.py -> build/lib.freebsd-12.1-RELEASE-p3-amd64-3.7/ueberzug
    copying ueberzug/layer.py -> build/lib.freebsd-12.1-RELEASE-p3-amd64-3.7/ueberzug
    copying ueberzug/batch.py -> build/lib.freebsd-12.1-RELEASE-p3-amd64-3.7/ueberzug
    copying ueberzug/loading.py -> build/lib.freebsd-12.1-RELEASE-p3-amd64-3.7/ueberzug
    copying ueberzug/pattern.py -> build/lib.freebsd-12.1-RELEASE-p3-amd64-3.7/ueberzug
    copying ueberzug/__main__.py -> build/lib.freebsd-12.1-RELEASE-p3-amd64-3.7/ueberzug
    copying ueberzug/scaling.py -> build/lib.freebsd-12.1-RELEASE-p3-amd64-3.7/ueberzug
    copying ueberzug/ui.py -> build/lib.freebsd-12.1-RELEASE-p3-amd64-3.7/ueberzug
    copying ueberzug/xutil.py -> build/lib.freebsd-12.1-RELEASE-p3-amd64-3.7/ueberzug
    copying ueberzug/tmux_util.py -> build/lib.freebsd-12.1-RELEASE-p3-amd64-3.7/ueberzug
    copying ueberzug/thread.py -> build/lib.freebsd-12.1-RELEASE-p3-amd64-3.7/ueberzug
    copying ueberzug/geometry.py -> build/lib.freebsd-12.1-RELEASE-p3-amd64-3.7/ueberzug
    copying ueberzug/terminal.py -> build/lib.freebsd-12.1-RELEASE-p3-amd64-3.7/ueberzug
    copying ueberzug/action.py -> build/lib.freebsd-12.1-RELEASE-p3-amd64-3.7/ueberzug
    copying ueberzug/library.py -> build/lib.freebsd-12.1-RELEASE-p3-amd64-3.7/ueberzug
    copying ueberzug/parser.py -> build/lib.freebsd-12.1-RELEASE-p3-amd64-3.7/ueberzug
    creating build/lib.freebsd-12.1-RELEASE-p3-amd64-3.7/ueberzug/lib
    copying ueberzug/lib/__init__.py -> build/lib.freebsd-12.1-RELEASE-p3-amd64-3.7/ueberzug/lib
    creating build/lib.freebsd-12.1-RELEASE-p3-amd64-3.7/ueberzug/lib/v0
    copying ueberzug/lib/v0/__init__.py -> build/lib.freebsd-12.1-RELEASE-p3-amd64-3.7/ueberzug/lib/v0
    running egg_info
    writing ueberzug.egg-info/PKG-INFO
    writing dependency_links to ueberzug.egg-info/dependency_links.txt
    writing entry points to ueberzug.egg-info/entry_points.txt
    writing requirements to ueberzug.egg-info/requires.txt
    writing top-level names to ueberzug.egg-info/top_level.txt
    reading manifest file 'ueberzug.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'ueberzug.egg-info/SOURCES.txt'
    copying ueberzug/lib/lib.sh -> build/lib.freebsd-12.1-RELEASE-p3-amd64-3.7/ueberzug/lib
    running build_ext
    building 'Xshm' extension
    creating build/temp.freebsd-12.1-RELEASE-p3-amd64-3.7
    creating build/temp.freebsd-12.1-RELEASE-p3-amd64-3.7/Xshm
    cc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -fPIC -I/usr/local/include/python3.7m -c Xshm/Xshm.c -o build/temp.freebsd-12.1-RELEASE-p3-amd64-3.7/Xshm/Xshm.o
    Xshm/Xshm.c:5:10: fatal error: 'X11/Xlib.h' file not found
    #include <X11/Xlib.h>
             ^~~~~~~~~~~~
    1 error generated.
    error: command 'cc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/usr/local/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-ddm1lz4k/ueberzug/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2owdhoog/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-ddm1lz4k/ueberzug/

**Comment by seebye** [comment]
There's already an issue about this subject: https://github.com/seebye/ueberzug/issues/48
